# Generated by Django 4.2.7 on 2023-12-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'itinerario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('codigo', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('calidad', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('disponibilidad', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'transporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('numero_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_partida', models.DateField(blank=True, null=True)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('disponibilidad', models.CharField(blank=True, max_length=45, null=True)),
                ('hora_salida', models.DateField(blank=True, null=True)),
                ('hora_llegada', models.DateField(blank=True, null=True)),
                ('itinerario', models.ForeignKey(db_column='itinerario', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.itinerario')),
                ('transporte', models.ForeignKey(db_column='transporte', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.transporte')),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('idpasaje', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.IntegerField()),
                ('DNI', models.IntegerField(default='123')),
                ('estado', models.BooleanField(default=False)),
                ('servicio', models.ForeignKey(db_column='servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.servicio')),
            ],
            options={
                'db_table': 'pasaje',
                'managed': True,
            },
        ),
    ]
