# Generated by Django 4.2.7 on 2023-12-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_ciudad_options_alter_itinerario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='calidad_servicio',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='categoria',
        ),
        migrations.AddField(
            model_name='servicio',
            name='hora_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='calidad',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
